# Generated by Django 6.0.4 on 2026-05-13 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.TextField(max_length=20)),
                ('y_coordinate', models.FloatField()),
                ('x_coordinate', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='FirstFloor',
        ),
        migrations.AddField(
            model_name='connection',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_conn', to='Map.location'),
        ),
        migrations.AddField(
            model_name='connection',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_conn', to='Map.location'),
        ),
    ]
