# Generated by Django 6.0.4 on 2026-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_connection_location_delete_firstfloor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='floor_location',
            field=models.IntegerField(default=1),
        ),
    ]
