# Generated by Django 6.0.4 on 2026-05-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0003_location_floor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coordinates',
            field=models.JSONField(default=[]),
        ),
    ]
