# Generated by Django 6.0.4 on 2026-05-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0004_location_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=models.JSONField(default=list),
        ),
    ]
