# Generated by Django 6.0.4 on 2026-05-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0005_alter_location_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallwayNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_location', models.IntegerField(default=1)),
                ('hallway_point', models.TextField(max_length=20)),
                ('coordinates', models.JSONField(default=list)),
                ('y_coordinate', models.FloatField()),
                ('x_coordinate', models.FloatField()),
            ],
        ),
    ]
