# Generated by Django 6.0.4 on 2026-05-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0006_hallwaynodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HallwayNodes',
        ),
    ]
