# Generated by Django on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0007_delete_hallwaynodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='stair_type',
            field=models.CharField(
                blank=True,
                choices=[('entrance', 'Entrance'), ('exit', 'Exit')],
                max_length=10,
                null=True,
                help_text='Optional explicit stair direction for stair nodes.',
            ),
        ),
    ]
